name: Daily Data Ingestion

on:
  schedule:
    - cron: '0 2 * * *'   # Runs daily at 2:00 AM UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests tqdm

      - name: Run ingestion script
        env:
          API_URL: https://fraudguard-434w.onrender.com/predict/batch
          BATCH_SIZE: 100
          CSV_FILE: data/simulation.csv
        run: |
          python ingest_pipeline.py
