name: Daily Data Ingestion

on:
  schedule:
    - cron: '36 11 * * *'   # 1:36 PM your time
    - cron: '36 17 * * *'   # 7:36 PM your time
    - cron: '36 23 * * *'   # 1:36 AM your time
    - cron: '36 5 * * *'    # 7:36 AM your time
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests tqdm

      - name: Restore state cache
        uses: actions/cache@v3
        id: cache-state
        with:
          path: ingest_state.json
          key: ingest-state
          restore-keys: |
            ingest-state

      - name: Run ingestion script
        env:
          API_URL: https://fraudguard-434w.onrender.com/predict/batch
          BATCH_SIZE: 100
          DAILY_LIMIT: 100
          CSV_FILE: data/simulation.csv
        run: |
          python ingest_pipeline.py

      - name: Save state cache
        uses: actions/cache@v3
        with:
          path: ingest_state.json
          key: ingest-state
